import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import NavBar from "~/components/NavBar";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { data } = api.posts.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="w-full flex-row justify-center border-x md:max-w-7xl">
          <NavBar />

          {data?.map((post) => (
            <div
              key={post.id}
              className=" p-10 w-full justify-center"
            >
              <div className="border border-white p-3">
              <p className="text-xl font-semibold text-white">
                @{post.authorId}
              </p>
              <h1 className="text-3xl font-bold text-white">
                {post.title}
              </h1>
              <p className="text-xl text-white">{post.content}</p>

              </div>
            </div>
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
