import { useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import CreatePostWizard from "~/components/CreatePostWizard";
import LoadingSpinner from "~/components/LoadingSpinner";
import NavBar from "~/components/NavBar";
import PostView from "~/components/PostView";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { data, isLoading } = api.posts.getAll.useQuery();
  const { user, isLoaded: userLoaded } = useUser();
  if (isLoading) return <LoadingSpinner />;
  if (!data) return <div>Something Went Wrong</div>;
  const number = 2;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="w-full flex-row justify-center border-x md:max-w-7xl">
          <NavBar user={user} />
          <CreatePostWizard />

          {data?.map((fullPost) => (
            <PostView {...fullPost} key={fullPost.post.id} />
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
