import { useUser } from "@clerk/nextjs";
import { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import NavBar from "~/components/NavBar";

const PostPage: NextPage = () => {
  const { user, isLoaded: userLoaded } = useUser();
  const router = useRouter();
  const name = router.query.slug;
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="w-full flex-row justify-center border-x md:max-w-7xl">
          <NavBar user={user} />
        </div>
      </main>
    </>
  );
};
export default PostPage;
